chat/urls.py
# chat/urls.py
from django.urls import path

from . import views
from login_app import urls as login_apps

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

login_app/urls.py
from django.urls import path
from . import views


app_name = 'login_app'

urlpatterns = [
        path('', views.login, name='login'),
        path('signup/', views.signup, name='signup'),
        path('logout/', views.logout, name='logout'),
        path('password_reset/', views.password_reset, name='password_reset'),
        path('password_reset_secret/<str:secret>/', views.password_reset_secret, name='password_reset_secret'),
        path('password_reset_form/', views.password_reset_form, name='password_reset_form'),
]

pizza_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .api import PizzaList, PizzaDetail
from login_app import urls as login_app

app_name = "pizza_app"

urlpatterns = [
    path('', login_app.views.login, name='login'),
    path('customer_page', views.customer_page, name='customer_page'),
    path('employee_page/', views.employee_page, name='employee_page'),
    path('user_profile/', views.user_profile, name='user_profile'),  # new
    path('base/', views.base, name='base'),
    path('edit_pizza/<int:pk>/', views.edit_pizza, name='edit_pizza'),
    path('delete_pizza/', views.delete_pizza, name='delete_pizza'),
    path('update_pizza/', views.update_pizza, name='update_pizza'),
    path('thank_you/<int:pk>/', views.thank_you, name='thank_you'),
    path('api/v1/', PizzaList.as_view()),
    path('api/v1/<int:pk>/', PizzaDetail.as_view()),
    path('edit_customers/', views.edit_customers, name='edit_customers'),

]

pizza_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizza_app.urls')),
    path('accounts/', include('login_app.urls')),
    path('chat/', include('chat.urls')),
    path('notifications/', include('notifications.urls')),
]

pizza_app/models.py
from uuid import uuid4
from django.contrib.auth.models import User
from django.db import models
import random, _datetime

# CHANNELS FOR NOTIFICATION WHEN ORDER IS PLACED
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync

# DJANGO RQ FOR EMAIL WHEN ORDER IS PLACED
import django_rq
from . messaging import email_message, admin_order_email, user_order_email

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    telephone = models.CharField(max_length=35)
    status = (
        ('employee', 'employee'),
        ('customer', 'customer')
    )
    user_status = models.CharField(
        choices=status, default='customer', max_length=250)

    @classmethod
    def create_user(cls, username, password, email, telephone) -> User:
        user = None
        # Creating a new Django user and also referencing this new user in a variable to be used later down when creating a user profile
        user = User.objects.create_user(
            username=username, password=password, email=email)

        userProfile = cls()
        userProfile.user = user
        userProfile.telephone = telephone
        # Hardcoded testing creating user with customer status so we can test further and improve
        userProfile.user_status = "customer"
        userProfile.save()

        return user

    def __str__(self):
        return f'{self.user}'


class Pizza(models.Model):
    pizza_id = models.IntegerField(null=False, default="0")
    name = models.CharField(max_length=250)
    text = models.CharField(max_length=250)
    price = models.IntegerField(default=0)

    @classmethod
    def create(cls, pizza_id, name, text, price):
        pizza = cls()
        pizza.pizza_id = random.randint(100000, 400000)
        pizza.name = name
        pizza.text = text
        pizza.price = price
        pizza.save()

    def __str__(self):
        return f"{self.name}"

class Topping(models.Model):
     item = models.CharField(max_length=64, unique=True, blank=False)
     price = models.IntegerField(default=0)

     def __str__(self):
        return f'{self.item}'

class Order(models.Model):
    status = (
        ('pending', 'pending'),
        ('delivering', 'delivering'),
        ('delivered', 'delivered'),
    )
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    order_date_time = models.DateTimeField(auto_now_add=True)
    delivery_date_time = models.DateTimeField(default='20:00')
    total_price = models.IntegerField(default=0)
    order_status = models.CharField(
        choices=status, default='pending', max_length=250)
    pizzas = models.CharField(max_length=250, default="Pepperoni")
    toppings = models.ManyToManyField(Topping, blank=True)

    @classmethod
    def create(cls, delivery_date_time, pizza_id, pizza_name, pizza_price, customer, topping):
        order = cls()
        order.delivery_date_time = delivery_date_time
        order.total_price = pizza_price
        order.customer = customer
        order.pizzas = pizza_name
        order.save()
        order.toppings.add(topping)

        # Using non class methods - rather methods on the instance that was created:
        order.create_order_notification()
        order.send_order_confirmation_emails()
        order.test_print()

        return order

    def create_order_notification(self):
        channel_layer = get_channel_layer()
        data = "Order #"+ str(self.pk) + " placed." # Pass any data based on your requirement
        # Trigger message sent to group
        async_to_sync(channel_layer.group_send)(
            str("Order_Notification_Group"),  # Group Name, Should always be string
            {
                "type": "notify",   # Custom Function written in the consumers.py
                "text": data,
            },
        )

    def send_order_confirmation_emails(self):
        django_rq.enqueue(admin_order_email, {
               'order_id' : str(self.pk),
               'email' : 'joshkap2015@gmail.com',
            })
        django_rq.enqueue(user_order_email, {
               'order_id' : str(self.pk),
               'email' : 'joshkap2015@gmail.com',
            })

    def test_print(self):
        print("Testing the print method. Order id: #" + str(self.pk))

    def __str__(self):
        return f"Order #{self.pk} - Pizzas: {self.pizzas}"

pizza_app/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.db.utils import IntegrityError
from django.contrib.auth import get_user_model
from .models import UserProfile, Pizza, Order, Topping
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
import random
from .utils import is_pizza_employee
from django.urls import reverse
from django.shortcuts import redirect

# EMAILS
import django_rq
from . messaging import email_message


def index(request):
    if is_pizza_employee(request.user):
        return HttpResponseRedirect(reverse('pizza_app:employee_page'))
    else:
        return HttpResponseRedirect(reverse('pizza_app:user_profile'))


@login_required
def customer_page(request):
    assert not is_pizza_employee(
        request.user), 'Employee routed to customer view.'
    pizzas = Pizza.objects.all()
    userProfiles = UserProfile.objects.filter(user=request.user)
    toppings = Topping.objects.all()

    context = {
        'toppings' : toppings,
        'pizzas': pizzas,
        'userProfiles': userProfiles,
    }

    if request.method == 'POST':
        # delivery_date_time user must specify
        delivery_date_time = request.POST['delivery_time']
        pizza_id = request.POST['pizza_id']
        pizza_name = request.POST['pizza_name']
        pizza_price = request.POST['pizza_price']
        topping_id = request.POST['topping_id']

        order = Order.create(delivery_date_time,
                            pizza_id, pizza_name, pizza_price, request.user, topping_id)
        context = {
            'order': order
        }                 
        return redirect('thank_you/'+ str(order.pk))

    return render(request, 'pizza_app/customer_page.html', context)


@login_required
def user_profile(request):
    if request.method == 'GET':
        # Getting only a single user profile object to pass through in the context, instead of an array which has to be looped through
        userProfile = UserProfile.objects.get(user=request.user)
        context = {
            'userProfile': userProfile,
        }
    return render(request, 'pizza_app/user_profile.html', context)


@login_required
def thank_you(request, pk):
    order = get_object_or_404(Order, pk=pk)
    context = {
        'order': order,
    }
    return render(request, 'pizza_app/thank_you.html', context)


@login_required
def employee_page(request):
    assert is_pizza_employee(request.user), 'Customer routed to employee view.'
    if request.method == 'POST':
        name = request.POST['pizza_name']
        text = request.POST['pizza_text']
        price = request.POST['pizza_price']
        pizza = Pizza()
        pizza.pizza_id = random.randint(100000, 199999)
        pizza.name = name
        pizza.text = text
        pizza.price = price
        pizza.save()
    pizzas = Pizza.objects.all()
    userProfiles = UserProfile.objects.filter(user=request.user)
    context = {
        'pizzas': pizzas,
        'userProfiles': userProfiles,
    }
    return render(request, 'pizza_app/employee_page.html', context)


@login_required
def base(request):
    userProfiles = UserProfile.objects.filter(user=request.user)
    context = {
        'userProfiles': userProfiles,
    }
    return render(request, 'pizza_app/base.html', context)


# edit PIZZA page
@login_required
def edit_pizza(request, pk):
    pizza = get_object_or_404(Pizza, pk=pk)
    context = {
        'pizza': pizza,
    }
    return render(request, 'pizza_app/edit_pizza.html', context)

# Delete PIZZA


def delete_pizza(request):
    pizza_id = request.POST['pizza_id']
    pizza = get_object_or_404(Pizza, pizza_id=pizza_id)
    pizza.delete()

    return HttpResponseRedirect(reverse('pizza_app:employee_page'))

# Update Pizza


def update_pizza(request):
    pizza_id = request.POST['pizza_id']
    pizza = get_object_or_404(Pizza, pizza_id=pizza_id)
    price = request.POST['pizza_price']
    text = request.POST['pizza_text']
    name = request.POST['pizza_name']
    pizza.price = price
    pizza.text = text
    pizza.name = name
    pizza.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


# CREATE ORDER

@login_required
def edit_customers(request):
    customers = get_user_model().objects.all()
    profiles = UserProfile.objects.all()
    context = {
        'customers': customers,
        'profiles': profiles,
    }
    return render(request, 'pizza_app/edit_customers.html', context)


@login_required
def create_order(request):
    pizzas = Pizza.objects.all()
    userProfiles = UserProfile.objects.filter(user=request.user)
    context = {
        'pizzas': pizzas,
        'userProfiles': userProfiles,
    }
    return render(request, 'pizza_app/edit_pizza.html', context)

pizza_app/templates/pizza_app/account_details.html
{% extends 'pizza_app/base.html' %} {% block title %}Account{% endblock %}
{% block content %}
<div class="accounts_text"><h1>Account details</h1></div>
<div class="transactions-text"><h1>Transactions</h1></div>
<section class="account-details">
<a href="{% url 'pizza_app:customer_page' %}">Home</a>
<hr />
<ul>
  {% for account in accounts %}

  <ul class="account-list">
    Account Name:
    {{ account.text }}
    Account number:
    {{ account.number }}
    Your Balance
    {{ account.balance }}
  </ul>


  <form action="{% url 'pizza_app:account_withdraw' %}" method="POST">
    {% csrf_token %}
    <p>Withdraw</p>
    <input type="hidden" name="account_number" value="{{account.number}}" />
    <input type="number" placeholder="Amount" name="withdraw_amount" required max="{{account.balance}}"/>
    <input type="submit" value="Withdraw" />
  </form>

  <form action="{% url 'pizza_app:account_deposit' %}" method="POST">
    {% csrf_token %}
    <p>Deposit</p>
    <input type="hidden" name="account_number" value="{{account.number}}" />
    <input type="number" placeholder="Amount" name="deposit_amount" required min="1"/>
    <input type="submit" value="Deposit" />
  </form>
</section>
  <style>
    .account-list {
      display: grid;
      grid-template-columns: repeat(8, 1fr);
      grid-column-gap: 25px;
      margin-top: 10px;
      margin-bottom: 10px;
    }
  </style>
  {% endfor %}
</ul>

<div class="account-log">

{% for accountTransaction in accountTransactions %}

<div class="transaction-table">
  <div><b>Transaction ID</b></div>
  <div><b>Transaction Type</b></div>
  <div><b>Amount</b></div>
  <div><b>Balance</b></div>
  <div>{{ accountTransaction.transactionID }}</div>

  <div>{{ accountTransaction.transactionType }}</div>
  {% if accountTransaction.transactionType == "Withdraw" %}
    <div style="color:red;">- {{ accountTransaction.transactionAmount }}</div>
  {% elif accountTransaction.transactionType == "Transfer Out"%}
    <div style="color:red;">- {{ accountTransaction.transactionAmount }}</div>
  {% elif accountTransaction.transactionType == "Deposit" %}
    <div style="color:green;">+ {{ accountTransaction.transactionAmount }}</div>
  {% elif accountTransaction.transactionType == "Transfer In" %}
    <div style="color:green;">+ {{ accountTransaction.transactionAmount }}</div>
  {% elif accountTransaction.transactionType == "Initial Deposit" %}
    <div style="color:green;">+ {{ accountTransaction.transactionAmount }}</div>
  {% endif %}

  <div>{{ accountTransaction.balance }}</div>

</div>
</div>
<style>
  .transaction-table {
    display:grid;
    grid-template-columns:1fr 1fr 1fr 1fr;
    margin-bottom:10px;
  }
</style>
{% endfor %}
{% endblock %}

pizza_app/templates/pizza_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'pizza_app/style.css' %}" media="screen" />
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Cardo&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  <div class="topbar">
    Free delivery on orders above 99kr
  </div>
  <nav class="topnav">
      <h1 class="shop-name">Pizza Express</h1>
    {% for userProfile in userProfiles %}
    {% if user.is_authenticated and userProfile.user_status == 'employee' %}
    <a class="btn" href="{% url 'pizza_app:employee_page' %}">Home</a>
    <a class="btn" href="{% url 'pizza_app:edit_customers' %}">Edit Customer Profiles</a>
    <a class="nav-link2" href="{% url 'login_app:logout' %}">Log out <span data-feather="log-out"></a>
    {% elif user.is_authenticated and userProfile.user_status == 'customer' %}
    <a class="btn" href="{% url 'pizza_app:customer_page' %}">Home</a>
    <a class="nav-link2" href="{% url 'login_app:logout' %}">Log out <span data-feather="log-out"></a>
    {% comment %}
      Notifications div to be appended to by notifications
    {% endcomment %}
    <div style="margin-left:auto; width:100%; max-width:300px; position:relative; display:flex; flex-direction:column; align-items:center; justify-content:center;">
      <p style="display:block; margin:auto;"> Notifications</p>

      <div class="notifications-wrapper" style="width:100%;">
        <div class="notifications-container" style="position:absolute;">
          <!-- Notifications go here -->
        </div>
      </div>
      
    </div>
    {% endif %}
    {% endfor %}

    {% if user.is_not_authenticated %}
    <a class="nav-link2" href="{% url 'login_app:login' %}">Login <span data-feather="log-in"></a>
    <a class="btn" href="{% url 'login_app:signup' %}">Sign up</a>
    {% endif %}

  </nav>

  {% block content %} {% endblock %} {% block footer %} {% endblock %}
  <script>
    /* Connecting to notifications socket, same as routing.py in notifications folder ... */
    const notificationSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/notifications/'
        );

    // Socket should be connected now, now we can run functions on the socket instance.

    // Socket On receive message Functionality
    notificationSocket.onmessage = function(e){
        console.log('message', e)
        console.log(e.data) // Access the notification data

        const notificationContainer = document.querySelector(".notifications-container");

        let notificationDiv = document.createElement("div");
        

        notificationDiv.classList.add("notification-div");

        notificationDiv.innerHTML = "<p class='notification-p'>"+e.data+"</p>"

        notificationContainer.appendChild(notificationDiv)

        /* setTimeout(() => {
          notificationDiv.remove();
        }, 5000);
        */

    }

    // Socket Connet Functionality
    notificationSocket.onopen = function(e){
        console.log('Notification socket - open', e)
        console.log('Socket is opened.')
    }

    // Socket Error Functionality
    notificationSocket.onerror = function(e){
        console.log('Notification socket - error', e)
    }

    // Socket close Functionality
    notificationSocket.onclose = function(e){
        console.log('Notification socket - closed', e)
    }
</script>



<style>

  .notification-div {
    background-color:white;
    padding-top:10px;
    padding-bottom:10px;
    width:100%;
    max-width:200px;
    padding-left:20px;
    padding-right:20px;
    box-shadow: 10px 10px 25px rgba(0,0,0,.14);
    transition: box-shadow .3s ease-in-out;
    cursor:pointer;
    margin:0 auto;
  }

  .notifications-container {
    display:grid;
    width:100%;
    grid-row-gap:10px;
    transition: all .3s ease-in-out;
  }

  .topbar {
    border-bottom:1px solid black;
    text-align:center;
    font-family: 'Montserrat', sans-serif;
    padding-top:10px;
    padding-bottom:10px;
    font-size:12px;
  }

  .topnav a {
    color:black;
    text-decoration:none;
    display:flex;
    align-items:center;
    margin-left:10px;

  }

  .topnav {
    display:flex !important;
    padding-left:40px;
    padding-right:40px;
    border-bottom:2px solid white;
  }

  .shop-name {
    font-size:30px;
    color:black;
    font-family: 'Cardo', serif;
    padding:0;
    margin-right:20px;
  }

  .topnav img {
    width:40px;
    height:40px;
  }
</style>
</body>
</html>

pizza_app/templates/pizza_app/customer_page.html
{% extends 'pizza_app/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<section class="user_page">
    {% csrf_token %}
    <div class="menu_container">

        {% load static %}

        {% for userProfile in userProfiles %}
        <p class="greeting-text">Hello <b>{{ user.username }}</b> ({{ userProfile.user_status }})</p>
        <a class="profile-details-btn" style="color:black;" href="{% url 'pizza_app:user_profile' %}" style="color:white !important">View Profile Details</a>
        {% endfor%}

        <form action="">

        </form>
        <div class="hero-wrapper">
            <div>
                <h1 class="hero-header">Traditional fresh pizza since 2020.</h1>
            </div>
            <div style="width:100%;">
                <img class="hero-img" src="{% static 'pizza_app/img/ingredients.png' %}" alt="">
            </div>
        </div>
        <div class="pizzas-bg">
        <div class="pizzas-wrapper">

        
        {% for pizza in pizzas %}
        <form method="POST" class="pizza-block">
            {% csrf_token %}
            <input type="hidden" name="pizza_id" value="{{pizza.pizza_id}}" />
            <input type="hidden" name="pizza_price" value="{{pizza.price}}" />
            <input type="hidden" name="pizza_name" value="{{pizza.name}}" />

            <div class="pizza-content">
                <div>
                    <h2 class="pizza-name">{{ pizza.name }}</h2>
                    <p>{{ pizza.price }} kr.</p>
                    <p class="pizza-text">{{ pizza.text }}</p>

                </div>
                <div class="pizza-img">
                    <img src="//s3-eu-west-1.amazonaws.com/plantjammerbackend1/__sized__/pizzamexican-70f29787aa65faca2cbf20d354296030.jpg" alt="">
                </div>
            </div>
            
            <label for="delivery_time" id="start">Delivery time (date and time): </label>
            <input type="datetime-local" name="delivery_time" min="2010-06-12T00:00" max="2021-06-12T00:00" required>
            <label for="topping-choice">Select one additional topping</label>
            <select name="topping_id" style="margin-bottom:10px;">
              
                {% for topping in toppings %}
                    <option value="{{ topping.pk }}">{{ topping.item }} - {{ topping.price }} kr.</option>
                {% endfor %}
            </select>
            <button>Order</button>
        </form>
        {% endfor %}
        </div>
         </div>
        <a href="{% url 'login_app:logout' %}">Logout</a>
    </div>

    <div class="img_container">

    </div>
</section>

<style>

    .profile-details-btn {
        text-align:center;
        margin:0 auto;
        display:block;
        font-size:10px;
    }

    .greeting-text {
        text-align:center;
    }

    .pizzas-bg {
        background-color:#FFFBF6;
        padding-top:40px;
        padding-bottom:40px;
    }
    p {
        font-family: 'Montserrat', sans-serif;
    }
.pizzas-wrapper {
    max-width:1000px;
    margin: 0 auto;
    display:grid;
    grid-template-columns: 1fr 1fr;
    grid-column-gap:40px;
}

.hero-wrapper {
    max-width:1000px;
    margin:0 auto;
    display:grid;
    grid-template-columns: 1fr 1fr;
}

.hero-img {
    width:70%;
    display:block;
    margin:0 auto;
}

.hero-header{
    font-size:86px;
    line-height:90px;
    font-family: 'Cardo', serif;
    font-weight:400;
}

.pizza-name {
    font-family: 'Cardo', serif;
    margin-bottom: 1rem;
    font-weight:400 !important;
}

.pizza-text {
    color:#746b60;
    line-height:1.5em;
    height:3em;
    overflow:hidden;

    text-overflow: ellipsis !important;
    
}

.pizza-content {
    display:grid;
    grid-template-columns:1fr 0.5fr;
}

.pizza-img { 
    width:100%;
}

.pizza-img img {
    width:60%;
    display:block;
    margin-left:auto;
    
}

.user_page {
background-color:#FAF3EC;

}

.pizza-block {

    padding:20px;
    border-bottom:1px solid #746b605e;
}

.pizza-block:hover {
    box-shadow: 10px 10px 25px rgba(0,0,0,.14);
    transition: box-shadow .3s ease-in-out;
    cursor:pointer;
}

.pizza-block:hover .pizza-name {
    text-decoration:underline;
}

</style>


</body>

</html>
{% endblock %}

pizza_app/templates/pizza_app/edit_pizza.html
{% extends 'pizza_app/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<section class="edit_pizza">
  <h1>Edit Pizza</h1>


  <form method="POST">
    {% csrf_token %}
    <input type="hidden" name="pizza_id" value="{{pizza.pizza_id}}" placeholder="{{pizza.pizza_id}}" />
    <label for="lname">Pizza name:</label><br>
    <input type="text" name="pizza_name" value="{{pizza.name}}" placeholder="{{pizza.name}}" /> <br>
    <label for="lname">Pizza description:</label><br>
    <textarea type="text" name="pizza_text" value="{{pizza.text}}" placeholder="{{pizza.text}}"></textarea> <br>
    <label for="lname">Pizza Price:</label><br>
    <input type="number" name="pizza_price" value="{{pizza.price}}" placeholder="{{pizza.price}}" /><br><br>

    <button class="button" formaction="{% url 'pizza_app:delete_pizza' %}">Delete pizza</button>
    <button class="button" formaction="{% url 'pizza_app:update_pizza' %}">Update pizza</button>

    <input type="hidden" name="pizza_id" value="{{pizza.pizza_id}}">

  </form>
  <hr />
  <a class="home-btn" href="{% url 'pizza_app:employee_page' %}">Home</a>

</section>
</body>

</html>
{% endblock %}

pizza_app/templates/pizza_app/employe_page.html
{% extends 'pizza_app/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
{% for userProfile in userProfiles %}
{% if userProfile.user_status == "employee" %}

<section class="employe_page">
  <a href="{% url 'login_app:user_profile' %}">View Profile Details</a>

  {% for userProfile in userProfiles %}
  <h2>Helloooooo {{ user.username }}. {{ userProfile.user_status }}</h2>
  {% endfor%}
  <hr />

  <!-- CREATE NEW PIZZA -->

  <div class="new_pizza_container">
    <h1>Add new Pizza</h1>
    <form action="." method="POST">
      {% csrf_token %}
      <input type="text" placeholder="Name" name="pizza_name" />
      <input type="text" placeholder="Text" name="pizza_text" />
      <input type="number" placeholder="Price" name="pizza_price" />
      <br>
      <input type="submit" value="Add" class="pink-btn" />
    </form>
  </div>

  {% for pizza in pizzas %}
  <h2>Pizza name: {{ pizza.name }} <br> Pizza Description {{ pizza.text }} <br> Price: {{ pizza.price }} kr.</h2>
  <a href="{% url 'pizza_app:edit_pizza' %}">edit pizza</a>
  {% csrf_token %}
  {% endfor %}

</section>
</body>

</html>

{% else %}

<p>Not employee</p>
{% endif %}
{% endfor %}
{% endblock %}

pizza_app/templates/pizza_app/employee_page.html
{% extends 'pizza_app/base.html' %}

{% block title %}Edit pizza{% endblock %}

{% block content %}
{% for userProfile in userProfiles %}
{% if userProfile.user_status == "employee" %}

<section class="employe_page">

  {% load static %}

  {% for userProfile in userProfiles %}
  <p class="greeting-text">Hello <b>{{ user.username }}</b> ({{ userProfile.user_status }})</p>
  <a class="profile-details-btn" style="color:black;" href="{% url 'pizza_app:user_profile' %}"
    style="color:white !important">View Profile Details</a>
  {% endfor%}


  <!-- CREATE NEW PIZZA -->

  <div class="new_pizza_container">
    <h1>Add new Pizza</h1>
    <form action="." method="POST">
      {% csrf_token %}
      <input type="text" placeholder="Name" name="pizza_name" />
      <input type="text" placeholder="Text" name="pizza_text" />
      <input type="number" placeholder="Price" name="pizza_price" />
      <br>
      <input type="submit" value="Add" />
    </form>
  </div>
  <div class="white_line"></div>
  <br>

  <div class="pizzas-wrapper">
  {% for pizza in pizzas %}
  <div class="pizza-block">
    <div class="pizza-content2">
      <div>
        <h2 class="pizza-name">{{ pizza.name }}</h2>
        <p>{{ pizza.price }} kr.</p>
        <p class="pizza-text">{{ pizza.text }}</p>
        <a class="edit-pizza-btn" href="{% url 'pizza_app:edit_pizza' pizza.pk %}">Edit pizza</a>
      </div>

      <div class="pizza-img">
        <img
          src="//s3-eu-west-1.amazonaws.com/plantjammerbackend1/__sized__/pizzamexican-70f29787aa65faca2cbf20d354296030.jpg"
          alt="">
      </div>
    </div>
  </div>

  {% endfor %}
</div>
</section>
<style>
  .pizzas-wrapper {
    max-width:1000px;
    margin: 0 auto;
    display:grid;
    grid-template-columns: 1fr 1fr;
    grid-column-gap:40px;
}
</style>

{% else %}

<p>Not employee</p>
{% endif %}
{% endfor %}
{% endblock %}

pizza_app/templates/pizza_app/index.html
{% extends 'pizza_app/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<section class="user_page">
    <div class="menu_container">
        <h1>Menu</h1>

        <a href="{% url 'login_app:user_profile' %}">View Profile Details</a>

        {% for userProfile in userProfiles %}
        <h2>Helloooooo {{ user.username }}. {{ userProfile.user_status }}</h2>
        {% endfor%}


        {% for pizza in pizzas %}
        <h2>Pizza name: {{ pizza.name }} <br> Pizza Description: {{ pizza.text }} <br> Price: {{ pizza.price }} kr.</h2>
        {% endfor %}
    </div>

    <div class="img_container">

    </div>
</section>


</body>

</html>
{% endblock %}