chat/urls.py
# chat/urls.py
from django.urls import path

from . import views
from login_app import urls as login_apps

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

login_app/urls.py
from django.urls import path
from . import views


app_name = 'login_app'

urlpatterns = [
        path('', views.login, name='login'),
        path('signup/', views.signup, name='signup'),
        path('logout/', views.logout, name='logout'),
        path('password_reset/', views.password_reset, name='password_reset'),
        path('password_reset_secret/<str:secret>/', views.password_reset_secret, name='password_reset_secret'),
        path('password_reset_form/', views.password_reset_form, name='password_reset_form'),
]

pizza_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .api import PizzaList, PizzaDetail
from login_app import urls as login_app

app_name = "pizza_app"

urlpatterns = [
    path('', login_app.views.login, name='login'),
    path('customer_page', views.customer_page, name='customer_page'),
    path('employee_page/', views.employee_page, name='employee_page'),
    path('user_profile/', views.user_profile, name='user_profile'),  # new
    path('base/', views.base, name='base'),
    path('edit_pizza/<int:pk>/', views.edit_pizza, name='edit_pizza'),
    path('delete_pizza/', views.delete_pizza, name='delete_pizza'),
    path('update_pizza/', views.update_pizza, name='update_pizza'),
    path('thank_you/<int:pk>/', views.thank_you, name='thank_you'),
    path('api/v1/', PizzaList.as_view()),
    path('api/v1/<int:pk>/', PizzaDetail.as_view()),
    path('edit_customers/', views.edit_customers, name='edit_customers'),

]

pizza_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizza_app.urls')),
    path('accounts/', include('login_app.urls')),
    path('chat/', include('chat.urls')),
    path('notifications/', include('notifications.urls')),
]

login_app/models.py
from django.db import models
from django.contrib.auth.models import User
from secrets import token_urlsafe

from pizza_app.models import UserProfile

# New, simplified models, no need for user profile here.

class PasswordResetRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    secret = models.CharField(max_length=43, default=token_urlsafe)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    updated_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user} - {self.created_timestamp}'

login_app/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.models import User
from django.db.utils import IntegrityError
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from . import models
from pizza_app.models import UserProfile


def login(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        userProfile = UserProfile.objects.get(user=user) # Finds user profile and references in variable to be used below

        # If a user is matched
        if user: 
            if userProfile.user_status != 'employee':
                dj_login(request, user)
                return HttpResponseRedirect(reverse('pizza_app:customer_page')) # new
            elif UserProfile.user_status != 'customer':
                dj_login(request, user)
                return HttpResponseRedirect(reverse('pizza_app:employee_page')) # new
        else:
            context = {'error': 'Bad username or password.'}
    return render(request, 'login_app/login.html', context)


def logout(request):
    dj_logout(request)
    return HttpResponseRedirect(reverse('login_app:login'))


def password_reset(request):
    context = {}

    if request.method == "POST":
        email = request.POST['email']
        user = User.objects.get(email=email)
        reset_request = models.PasswordResetRequest()
        reset_request.user = user
        reset_request.save()
        url = reverse('login_app:password_reset_secret',
                      args=[f'{reset_request.secret}'])
        url = f'{request.scheme}://{request.META["HTTP_HOST"]}{url}'
        print(url)
        context = {
            'message': 'Please click the link in the email we sent to you.'}

    return render(request, 'login_app/password_reset.html', context)


def password_reset_secret(request, secret):
    context = {'secret': secret}
    return render(request, 'login_app/password_reset_form.html', context)


def password_reset_form(request):
    email = request.POST['email']
    password = request.POST['password']
    confirm_password = request.POST['confirm_password']
    secret = request.POST['secret']
    user = User.objects.get(email=email)
    reset_request = models.PasswordResetRequest.objects.get(
        user=user, secret=secret)
    if password == confirm_password:
        user.set_password(password)
        user.save()
        reset_request.save()
        return HttpResponseRedirect(reverse('login_app:login'))
    context = {
        'error': 'Something went wrong, try again, don\'t screw up this time!'}
    return render(request, 'login_app/password_reset_form.html', context)


# signup naming changed
def signup(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        email = request.POST['email']
        telephone = request.POST['telephone_number']

        if password == confirm_password:
            # New try function, to try creating a new user via the userProfile @classmethod create_user . Remember inside this @classmethod we are creating the Django User object too.
            try:
                UserProfile.create_user(username, password, email, telephone)
                return HttpResponseRedirect(reverse('login_app:login'), context)

            # If the try fails then send context that we could not create a user account
            except IntegrityError:
                context['error'] = 'Could not create user account.'
        else:
            # If passwords do not match.
            context = {'error': 'Passwords do not match.'}
    return render(request, 'login_app/signup.html', context)




def delete_account(request):
    pass

login_app/templates/login_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'login_app/style.css' %}" media="screen" />
  <link href="https://fonts.googleapis.com/css2?family=Cardo&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  <nav class="topnav">
    <h1 class="shop-name" style="color:black;">Pizza Express</h1>
    {% if user.is_authenticated%}
    <a class="btn" href="{% url 'pizza_app:customer_page' %}">Home</a>
    {% else %}
    <a class="btn" href="{% url 'login_app:login' %}">Home</a>
    <a class="btn" href="{% url 'login_app:signup' %}">Sign up</a>
    {% endif %}

    {% if user.is_authenticated %}
    <a class="nav-link2" href="{% url 'login_app:logout' %}">Log out <span data-feather="log-out"></a>
    {% else %}
    <a class="nav-link2" href="{% url 'login_app:login' %}">Log in <span data-feather="log-in"></a>
    {% endif %}
  </nav>

  {% block content %} {% endblock %} {% block footer %} {% endblock %}
</body>


<style>
  .topbar {
    border-bottom:1px solid black;
    text-align:center;
    font-family: 'Montserrat', sans-serif;
    padding-top:10px;
    padding-bottom:10px;
    font-size:12px;
  }

  .topnav a {
    color:black;
    text-decoration:none;
    display:flex;
    align-items:center;
    margin-left:10px;

  }

  .topnav a:hover {
    text-decoration:underline !important;
  }

  .topnav {
    display:flex !important;
    padding-left:40px;
    padding-right:40px;
    border-bottom:2px solid white;
  }

  .shop-name {
    font-size:30px;
    font-family: 'Cardo', serif;
    padding:0;
    margin-right:20px;
  }

  .topnav img {
    width:40px;
    height:40px;
  }
</style>

</html>

login_app/templates/login_app/login.html
{% extends 'login_app/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}


<section class="login">
  <div class="login_container">
    <h1 class="header">Login</h1>

    <a href="{% url 'login_app:password_reset' %}">Reset Password</a>

    <form action="{% url 'login_app:login' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="username" placeholder="Username" />
      <br />
      <input type="password" name="password" placeholder="Password" />
      <br />
      <input type="submit" value="Login" />
    </form>

  </div>
  <div class="img_container">

  </div>
</section>

{% if error %}
<p style="color: red">{{ error }}</p>
{% endif %}
</body>
{% endblock %}

login_app/templates/login_app/password_reset.html
{% extends 'login_app/base.html' %}

{% block title %}Password reset{% endblock %}

{% block content %}
<div style="margin:0 auto; max-width:1000px;">
    <h1>Password Reset</h1>
    <section class="password">

    <a href="{% url 'login_app:login' %}">Log In</a>
    <hr />

    <form action="{% url 'login_app:password_reset' %}" method="POST">
      {% csrf_token %}
      <input type="email" name="email" placeholder="Email" />
      <input type="submit" value="Reset Password" />
    </form>
    <hr />
  </div>
  </section>
    {% if message %}{{ message }}{% endif %}
  </body>
  {% endblock %}

login_app/templates/login_app/password_reset_form.html
{% extends 'login_app/base.html' %}

{% block title %}Password reset {% endblock %}

{% block content %}
    <h1>New Password</h1>
    <hr />
    <form action="{% url 'login_app:password_reset_form' %}" method="POST">
      {% csrf_token %}
      <input type="email" name="email" placeholder="Email Address" />
      <input type="password" name="password" placeholder="Password" />
      <input
        type="password"
        name="confirm_password"
        placeholder="Confirm Password"
      />
      <input type="hidden" name="secret" value="{{ secret }}" />
      <input type="submit" value="Set New Password" />
    </form>
    <hr />
    {% if error %}{{ error }}{% endif %}
  </body>
  {% endblock %}

login_app/templates/login_app/sign_up.html
{% extends 'login_app/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}

<section class="signup">
  <div class="signup_container">
    <h1>Sign Up</h1>
    <hr />
    <form action="{% url 'login_app:sign_up' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="username" placeholder="User Name" />
      <input type="password" name="password" placeholder="Password" />
      <input type="password" name="confirm_password" placeholder="Confirm Password" />
      <input type="email" name="email" placeholder="Email Address" />
      <input type="phone" name="telephone_number" placeholder="Telephone number" />
      <br>
      <input type="submit" value="Sign Up" />
    </form>
  </div>
</section>
</body>

{% endblock %}

login_app/templates/login_app/signup.html
{% extends 'login_app/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}

<section class="signup">
  <div class="signup_container">
    <h1>Sign Up</h1>
    <hr />
    <form action="{% url 'login_app:signup' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="username" placeholder="User Name" />
      <input type="password" name="password" placeholder="Password" />
      <input type="password" name="confirm_password" placeholder="Confirm Password" />
      <input type="email" name="email" placeholder="Email Address" />
      <input type="phone" name="telephone_number" placeholder="Telephone number" />
      <br>
      <input type="submit" value="Sign Up" />
    </form>
  </div>
</section>
</body>

{% endblock %}

login_app/templates/login_app/user_profile.html
{% extends 'login_app/base.html' %}

{% block title %}User Profile{% endblock %}

{% block content %}

    <h1>User profile</h1>
    Hello, {{ user.username }}.

    <form method="POST">
      {% csrf_token %}
      <input type="hidden" name="username" value="{{user.username}}" />
    </form>
    {% for userProfile in userProfiles %}
    <ul class="user-list">
      <li>User phone number:</li>
      {{ userProfile.telephone_number }}
      <li>Your Ranking is:</li>
      {{ userProfile.user_rank }}
    </ul>
    {% endfor %}
  </body>
  {% endblock %}